// Generated by CoffeeScript 1.6.3
(function() {
  var hashColor;

  if (typeof isNodeJs === "undefined" || typeof runTest === "undefined") {
    (function() {
      var root;
      root = typeof global === "undefined" ? window : global;
      if (typeof isNodeJs === "undefined") {
        root.isNodeJs = typeof window === "undefined";
      }
      if (typeof runTest === "undefined") {
        return root.runTest = isNodeJs && process.argv[2] === "test";
      }
    })();
  }

  hashColor = {};

  hashColor.strHash = function(s) {
    var hash, i;
    hash = 5381;
    i = s.length;
    while (i) {
      hash = (hash * 31 + s.charCodeAt(--i)) | 0;
    }
    return hash;
  };

  hashColor.prng = function(n) {
    return (1664525 * n + 1013904223) | 0;
  };

  hashColor.intToColor = function(i) {
    return "#" + ((i & 0xffffff) + 0x1000000).toString(16).slice(1);
  };

  hashColor.val = function(str) {
    return hashColor.prng(hashColor.strHash(str));
  };

  hashColor.light = function(str) {
    return hashColor.intToColor(((hashColor.val(str)) >> 4) | 0xe0e0e0);
  };

  hashColor.dark = function(str) {
    return hashColor.intToColor((hashColor.val(str)) & 0x7f7f7f);
  };

  if (isNodeJs) {
    module.exports = hashColor;
  } else {
    window.hashColor = hashColor;
  }

}).call(this);
