// Generated by CoffeeScript 1.6.3
(function() {
  var hashcolor;

  if (typeof isNodeJs === "undefined" || typeof runTest === "undefined") {
    (function() {
      var root;
      root = typeof global === "undefined" ? window : global;
      if (typeof isNodeJs === "undefined") {
        root.isNodeJs = typeof window === "undefined";
      }
      if (typeof runTest === "undefined") {
        return root.runTest = isNodeJs && process.argv[2] === "test";
      }
    })();
  }

  hashcolor = {};

  hashcolor.strHash = function(s) {
    var hash, i;
    hash = 5381;
    i = s.length;
    while (i) {
      hash = (hash * 31 + s.charCodeAt(--i)) | 0;
    }
    return hash;
  };

  hashcolor.prng = function(n) {
    return (1664525 * n + 1013904223) | 0;
  };

  hashcolor.intToColor = function(i) {
    return "#" + ((i & 0xffffff) + 0x1000000).toString(16).slice(1);
  };

  hashcolor.val = function(str) {
    return hashcolor.prng(hashcolor.strHash(str));
  };

  hashcolor.light = function(str) {
    return hashcolor.intToColor(((hashcolor.val(str)) >> 4) | 0xe0e0e0);
  };

  hashcolor.dark = function(str) {
    return hashcolor.intToColor((hashcolor.val(str)) & 0x7f7f7f);
  };

  if (isNodeJs) {
    module.exports = hashcolor;
  } else {
    window.hashcolor = hashcolor;
  }

}).call(this);
